name: Flask
link: https://flask.palletsprojects.com/en/3.0.x/patterns/
type: Library/Framework
projects:
  - name: Minos
    link: /projects/minos
jobs:
  - name: ANV
    link: https://anvproduction.pl/
