name: React
link: https://react.dev/
type: Library/Framework
projects:
  - name: Minos
    link: /projects/minos
  - name: lunar-stars
    link: /projects/lunar-stars
  - name: lunarify
    link: /projects/lunarify
jobs:
  - name: 4CF
    link: https://4cf.eu/
  - name: ANV
    link: https://anvproduction.pl/
